kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: spark-custom:7.7.7
          imagePullPolicy: "IfNotPresent"
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 2000m
          volumeMounts:
            - name: spark-data
              mountPath: "/mnt/app"
      volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: example-dataset

