apiVersion: batch/v1
kind: Job
metadata:
  name: spark-on-eks
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
        - name: spark-test
          image: gcr.io/spark-operator/spark:v3.1.1
          imagePullPolicy: Never
          command: [
            "/bin/sh",
            "-c",
            "/opt/spark/bin/spark-submit \
            --master k8s://https://staging-control-plane:6443 \
            --deploy-mode cluster \
            --name spark-on-eks \
            --class org.apache.spark.examples.SparkPi \
            --conf spark.executor.instances=5 \
            --conf spark.executor.memory=1G \
            --conf spark.kubernetes.executor.request.cores=0.1 \
            --conf spark.sql.shuffle.partitions=60 \
            --conf spark.kubernetes.container.image=gcr.io/spark-operator/spark:v3.1.1 \
            --conf spark.kubernetes.container.image.pullPolicy=Never \
            --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
            --conf spark.driver.host=$(hostname -i) \
            --conf spark.driver.pod.name=$(hostname) \
            --conf spark.jars.ivy=/tmp \
            local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
          ]
      serviceAccountName: spark
      restartPolicy: Never
  backoffLimit: 2


  # https://kubernetes.default.svc.cluster.local
  # connected to apiserver